name: run rspec
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup Database
        run: docker-compose run web rails db:create db:schema:load RAILS_ENV=test

      - name: Run RSpec
        run: docker-compose run web bundle exec rspec
